### ISSUE TITLE
ResourceObject should be render (__toString) before looking up headers

### ISSUE THREAD

**Issue by sasezaki** [bearsunday/BEAR.Middleware#1]
current [ResourceHandler](https://github.com/bearsunday/BEAR.Middleware/blob/3ab228c78572fd94b50236501ffd5741e8b43502/src/Handler/ResourceHandler.php) seems have issue for header setting.

Expected result

```
$ php -r 'var_dump(get_headers("http://localhost:8888/", 1)["Content-Type"]);'
string(16) "application/json"
```

Actual result

```
$ php -r 'var_dump(get_headers("http://localhost:8888/", 1)["Content-type"]);'
string(24) "text/html; charset=UTF-8"
```

Because, handle() method sets header such as below

``` php
        $response = $response->withStatus($resourceObject->code);
        foreach ($resourceObject->headers as $name => $value) {
            $response = $response->withHeader($name, $value);
        }
        $response->getBody()->write((string) $resourceObject);
```

I think fix needed like..

``` php
        $responseBody = (string) $resourceObject;
        $response = $response->withStatus($resourceObject->code);
        foreach ($resourceObject->headers as $name => $value) {
            $response = $response->withHeader($name, $value);
        }
        $response->getBody()->write($responseBody);
```

**Comment by sasezaki** [comment]
But sorry, at first, I don't prefer __toString for Render for `PSR-7`. :angry: 
 (reason is wrote at http://sasezaki.hatenablog.com/entry/2015/03/07/195908 )

**Comment by koriym** [comment]
Agreed. Handler should be handle stream not body string.

Your code seems works fine. Would you send PR ?
https://gist.github.com/sasezaki/68670975fbb5ca5114ed
Then we can leave your contribution on repository.

Or I can fixed it later. Thank you for making the issue.

**Comment by sasezaki** [comment]
ok. I would try at this weekend.

**Comment by koriym** [comment]
Awesome !

**Comment by sasezaki** [comment]
sorry for late. I couldn't take a time to catch up lack of BEAR.Sunday knowledge.
so I want someone working on this.

**Comment by koriym** [comment]
no problem, I will do it later with your code.

**Comment by koriym** [comment]
quick fix for header now.

**Comment by koriym** [comment]
@sasezaki

> ResourceObject should be render (__toString) before looking up headers

Fixed ! 

> But sorry, at first, I don't prefer __toString for Render for PSR-7. :angry: 

Now `RequestHandler` returns 100% genuine stream response.

https://github.com/bearsunday/BEAR.Middleware/blob/51a93093a0164e1f0c326b12fdc8b69b59e2a251/src/Handler/ResourceHandler.php#L98

But things are not easy as first glance. The current implementation has limitation. This version can't handle with your blog post example. (view template produce huge text). 

Instead, we can assign `stream` resource at `ResourceObject`

``` php
    public function onGet()
    {
        $this['msg'] = 'hello world';
        $this['stream'] = fopen(__DIR__ . '/message.txt', 'r');
        return $this;
    }
```

`hello world` text and  `/message.txt` stream are placed at their place folder in layout file, then text parts(hello world and layout template) is converted to stream to merge native stream (message.txt). You can assign multiple stream in any place. All stream will be merged and streamed.

https://github.com/bearsunday/BEAR.Middleware/blob/1.x/src/Module/StreamRenderer.php#L117

If you want single stream without any fixed text, you simple assign stream to entire resource body. 

``` php
    public function onGet()
    {
        $this->body = fopen(__DIR__ . '/message.txt', 'r');
        return $this;
    }
```

**Comment by koriym** [comment]
@sasezaki I tested with huge text stream, It succeeded but need to change output procedure as you mentioned. 

![mwop-q](http://cdn-ak.f.st-hatena.com/images/fotolife/s/sasezaki/20150307/20150307190839.png)

**Comment by koriym** [comment]
@sasezaki your blog post are **SUPER** helpful. (I knew very little about it)
Huge thanks !!
